import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import boundaries from "eslint-plugin-boundaries";
import prettier from "eslint-config-prettier";

// Globals forbidden inside the OKLCH engine so it stays isomorphic — no DOM, no
// Node runtime. Framework imports (next/react) are caught by boundaries/external;
// these catch ambient global usage that imports can't.
const NON_ISOMORPHIC_GLOBALS = [
  "window",
  "document",
  "navigator",
  "location",
  "localStorage",
  "sessionStorage",
  "history",
  "process",
  "Buffer",
  "__dirname",
  "__filename",
  "global",
];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // The standalone Studio has its own ESLint config.
    "studio/**",
    // Agent-team worktrees (a first-class workflow here) are full repo checkouts
    // under this gitignored runtime dir; flat config doesn't read .gitignore, so
    // exclude them explicitly or `pnpm lint` scans every teammate's copy mid-run.
    ".claude/worktrees/**",
    // Generated by Sanity TypeGen.
    "sanity.types.ts",
  ]),
  // Architectural import boundaries (stood up empty — they guard directories that
  // don't exist yet so they can't rot once code arrives).
  {
    files: ["src/**/*.{js,jsx,ts,tsx,mts,cts}"],
    plugins: { boundaries },
    settings: {
      "boundaries/include": ["src/**/*"],
      // First match wins, so specific patterns precede the shared catch-all.
      // mode: "file" matches the full file path (folder mode compares the
      // directory, which makes a fixed-folder glob like the oklch one miss).
      "boundaries/elements": [
        { type: "app", mode: "file", pattern: "src/app/**/*" },
        {
          type: "project",
          mode: "file",
          pattern: "src/projects/*/**/*",
          capture: ["slug"],
        },
        // The resolver registry is the ONE sanctioned shared→project importer:
        // the contract mandates that a `componentKey` resolves to a literal
        // `() => import("@/projects/<slug>")` right here. Modeling the registry as its
        // own element — matched before the `shared` catch-all, since first match wins —
        // lets it import `project` modules while the `shared`→`project` ban below still
        // holds for every other shared module. Tightens the boundary to the one allowed
        // importer rather than loosening the rule wholesale.
        {
          type: "registry",
          mode: "file",
          pattern: "src/lib/resolvers/components.ts",
        },
        { type: "shared", mode: "file", pattern: "src/**/*" },
      ],
    },
    rules: {
      "boundaries/dependencies": [
        "error",
        {
          default: "allow",
          checkAllOrigins: true,
          rules: [
            {
              from: { type: "project" },
              disallow: {
                to: {
                  type: "project",
                  captured: { slug: "!{{from.captured.slug}}" },
                },
              },
              message:
                "A project module cannot import another project — lift shared code into a shared module.",
            },
            {
              from: { type: "shared" },
              disallow: { to: { type: "project" } },
              message:
                "Shared modules cannot import project code — dependencies point from projects to shared, never back.",
            },
          ],
        },
      ],
    },
  },
  // The OKLCH engine is its own workspace package (@garden/oklch) so the standalone
  // Studio can import it too. The isomorphism guard applies: no framework
  // imports, no DOM/Node runtime globals. `boundaries` is scoped to `src/**` and can't
  // reach here, so the framework-import ban is enforced via no-restricted-imports below.
  {
    files: ["packages/oklch/**/*.{js,jsx,ts,tsx,mts,cts}"],
    rules: {
      "no-restricted-globals": ["error", ...NON_ISOMORPHIC_GLOBALS],
      "no-restricted-imports": [
        "error",
        {
          paths: ["react", "react-dom", "server-only", "client-only"],
          patterns: ["next", "next/*", "react-dom/*"],
        },
      ],
    },
  },
  // Must come last: turns off any ESLint rules that would conflict with Prettier.
  prettier,
]);

export default eslintConfig;
