/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Figure = {
  _type: "figure";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type LiveEmbed = {
  _type: "liveEmbed";
  embedKey?: string;
  caption?: string;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & LiveEmbed)
  | ({
      _key: string;
    } & Figure)
>;

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  brandColor?: string;
  brandColorDark?: string;
  fontKey?: string;
};

export type EntryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "entry";
};

export type Entry = {
  _id: string;
  _type: "entry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "note" | "essay" | "project" | "now";
  title?: string;
  slug?: Slug;
  stage?: "sketch" | "prototype" | "shipped";
  iterated?: string;
  featuredRank?: number;
  blurb?: string;
  brandColor?: string;
  brandColorDark?: string;
  fontKey?: string;
  componentKey?: string;
  body?: PortableText;
  related?: Array<
    {
      _key: string;
    } & EntryReference
  >;
  tags?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Figure
  | LiveEmbed
  | PortableText
  | SiteSettings
  | EntryReference
  | Entry
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/app/notes/queries.ts
// Variable: NOTES_INDEX_QUERY
// Query: *[_type == "entry" && kind == "note" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    "relatedCount": count(related)  }
export type NOTES_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  relatedCount: number | null;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: WORK_INDEX_QUERY
// Query: *[_type == "entry" && kind == "project" && defined(slug.current)] | order(_createdAt desc) {    _id,    title,    "slug": slug.current,    kind,    stage,    featuredRank,    blurb,    brandColor,    fontKey  }
export type WORK_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  kind: "essay" | "note" | "now" | "project" | null;
  stage: "prototype" | "shipped" | "sketch" | null;
  featuredRank: number | null;
  blurb: string | null;
  brandColor: string | null;
  fontKey: string | null;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: PROJECT_DETAIL_QUERY
// Query: *[_type == "entry" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    kind,    stage,    iterated,    featuredRank,    blurb,    brandColor,    brandColorDark,    fontKey,    componentKey,    body,    related[]->{ _id, title, "slug": slug.current, kind },    "backlinks": *[_type == "entry" && references(^._id)]{ _id, title, "slug": slug.current, kind },    tags  }
export type PROJECT_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  kind: "essay" | "note" | "now" | "project" | null;
  stage: "prototype" | "shipped" | "sketch" | null;
  iterated: string | null;
  featuredRank: number | null;
  blurb: string | null;
  brandColor: string | null;
  brandColorDark: string | null;
  fontKey: string | null;
  componentKey: string | null;
  body: PortableText | null;
  related: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    kind: "essay" | "note" | "now" | "project" | null;
  }> | null;
  backlinks: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    kind: "essay" | "note" | "now" | "project" | null;
  }>;
  tags: Array<string> | null;
} | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    _id,    title,    description,    brandColor,    brandColorDark,    fontKey  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  title: string | null;
  description: string | null;
  brandColor: string | null;
  brandColorDark: string | null;
  fontKey: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "entry" && kind == "note" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    "relatedCount": count(related)\n  }\n': NOTES_INDEX_QUERY_RESULT;
    '\n  *[_type == "entry" && kind == "project" && defined(slug.current)] | order(_createdAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    kind,\n    stage,\n    featuredRank,\n    blurb,\n    brandColor,\n    fontKey\n  }\n': WORK_INDEX_QUERY_RESULT;
    '\n  *[_type == "entry" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    kind,\n    stage,\n    iterated,\n    featuredRank,\n    blurb,\n    brandColor,\n    brandColorDark,\n    fontKey,\n    componentKey,\n    body,\n    related[]->{ _id, title, "slug": slug.current, kind },\n    "backlinks": *[_type == "entry" && references(^._id)]{ _id, title, "slug": slug.current, kind },\n    tags\n  }\n': PROJECT_DETAIL_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    _id,\n    title,\n    description,\n    brandColor,\n    brandColorDark,\n    fontKey\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
