/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Quote = {
  _type: "quote";
  text?: string;
  attribution?: string;
};

export type Video = {
  _type: "video";
  url?: string;
  caption?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Figure = {
  _type: "figure";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Slot = {
  _type: "slot";
  slotKey?: string;
  caption?: string;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & Figure)
  | ({
      _key: string;
    } & Video)
  | ({
      _key: string;
    } & Slot)
  | ({
      _key: string;
    } & Quote)
>;

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  theme?: {
    color?: string;
    colorDark?: string;
  };
  pageThemes?: {
    home?: string;
    browse?: string;
    about?: string;
    now?: string;
    system?: string;
  };
};

export type EntryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "entry";
};

export type Entry = {
  _id: string;
  _type: "entry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "note" | "essay" | "demo" | "now";
  title?: string;
  slug?: Slug;
  stage?: "sketch" | "prototype" | "shipped";
  iterated?: string;
  featuredRank?: number;
  summary?: string;
  theme?: {
    color?: string;
    colorDark?: string;
    headingFont?: string;
    bodyFont?: string;
    monoFont?: string;
  };
  componentKey?: string;
  body?: PortableText;
  related?: Array<
    {
      _key: string;
    } & EntryReference
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Quote
  | Video
  | SanityImageAssetReference
  | Figure
  | Slot
  | PortableText
  | SiteSettings
  | EntryReference
  | Entry
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/lib/queries.ts
// Variable: ENTRY_FEED_QUERY
// Query: *[_type == "entry" && defined(slug.current)] | order(coalesce(iterated, _createdAt) desc) {    _id,    title,    "slug": slug.current,    summary,    "published": coalesce(iterated, _createdAt)  }
export type ENTRY_FEED_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  published: string;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: ENTRY_SLUGS_QUERY
// Query: *[_type == "entry" && defined(slug.current)]{ "slug": slug.current }
export type ENTRY_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: ENTRY_DETAIL_QUERY
// Query: *[_type == "entry" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    kind,    stage,    iterated,    featuredRank,    summary,    theme { color, colorDark, headingFont, bodyFont, monoFont },    componentKey,    "themeSeed": select(kind == "now" => *[_type == "siteSettings"][0].pageThemes.now, theme.color),    body,    related[]->{ _id, title, "slug": slug.current, kind },    "backlinks": *[_type == "entry" && references(^._id)]{ _id, title, "slug": slug.current, kind }  }
export type ENTRY_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  kind: "demo" | "essay" | "note" | "now" | null;
  stage: "prototype" | "shipped" | "sketch" | null;
  iterated: string | null;
  featuredRank: number | null;
  summary: string | null;
  theme: {
    color: string | null;
    colorDark: string | null;
    headingFont: string | null;
    bodyFont: string | null;
    monoFont: string | null;
  } | null;
  componentKey: string | null;
  themeSeed: string | null;
  body: PortableText | null;
  related: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    kind: "demo" | "essay" | "note" | "now" | null;
  }> | null;
  backlinks: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    kind: "demo" | "essay" | "note" | "now" | null;
  }>;
} | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: INDEX_QUERY
// Query: *[_type == "entry" && defined(slug.current) && kind != "now"] | order(kind asc, coalesce(iterated, _createdAt) desc) {    _id,    title,    "slug": slug.current,    kind,    stage,    summary,    "linkCount": count(array::unique(      coalesce(related[]->_id, []) + *[_type == "entry" && references(^._id)]._id    )[defined(@) && @ != ^._id])  }
export type INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  kind: "demo" | "essay" | "note" | "now" | null;
  stage: "prototype" | "shipped" | "sketch" | null;
  summary: string | null;
  linkCount: number;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: FEATURED_QUERY
// Query: *[_type == "entry" && defined(slug.current) && defined(featuredRank)] | order(featuredRank asc) {    _id,    title,    "slug": slug.current,    kind,    stage,    summary,    theme { color }  }
export type FEATURED_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  kind: "demo" | "essay" | "note" | "now" | null;
  stage: "prototype" | "shipped" | "sketch" | null;
  summary: string | null;
  theme: {
    color: string | null;
  } | null;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: NOW_QUERY
// Query: *[_type == "entry" && kind == "now" && defined(slug.current)] | order(coalesce(iterated, _createdAt) desc) {    _id,    title,    "slug": slug.current,    iterated,    summary,    "linkCount": count(array::unique(      coalesce(related[]->_id, []) + *[_type == "entry" && references(^._id)]._id    )[defined(@) && @ != ^._id])  }
export type NOW_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  iterated: string | null;
  summary: string | null;
  linkCount: number;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    _id,    title,    description,    pageThemes { home, browse, about, now, system }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  title: string | null;
  description: string | null;
  pageThemes: {
    home: string | null;
    browse: string | null;
    about: string | null;
    now: string | null;
    system: string | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "entry" && defined(slug.current)] | order(coalesce(iterated, _createdAt) desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    "published": coalesce(iterated, _createdAt)\n  }\n': ENTRY_FEED_QUERY_RESULT;
    '\n  *[_type == "entry" && defined(slug.current)]{ "slug": slug.current }\n': ENTRY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "entry" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    kind,\n    stage,\n    iterated,\n    featuredRank,\n    summary,\n    theme { color, colorDark, headingFont, bodyFont, monoFont },\n    componentKey,\n    "themeSeed": select(kind == "now" => *[_type == "siteSettings"][0].pageThemes.now, theme.color),\n    body,\n    related[]->{ _id, title, "slug": slug.current, kind },\n    "backlinks": *[_type == "entry" && references(^._id)]{ _id, title, "slug": slug.current, kind }\n  }\n': ENTRY_DETAIL_QUERY_RESULT;
    '\n  *[_type == "entry" && defined(slug.current) && kind != "now"] | order(kind asc, coalesce(iterated, _createdAt) desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    kind,\n    stage,\n    summary,\n    "linkCount": count(array::unique(\n      coalesce(related[]->_id, []) + *[_type == "entry" && references(^._id)]._id\n    )[defined(@) && @ != ^._id])\n  }\n': INDEX_QUERY_RESULT;
    '\n  *[_type == "entry" && defined(slug.current) && defined(featuredRank)] | order(featuredRank asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    kind,\n    stage,\n    summary,\n    theme { color }\n  }\n': FEATURED_QUERY_RESULT;
    '\n  *[_type == "entry" && kind == "now" && defined(slug.current)] | order(coalesce(iterated, _createdAt) desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    iterated,\n    summary,\n    "linkCount": count(array::unique(\n      coalesce(related[]->_id, []) + *[_type == "entry" && references(^._id)]._id\n    )[defined(@) && @ != ^._id])\n  }\n': NOW_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    _id,\n    title,\n    description,\n    pageThemes { home, browse, about, now, system }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
